// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnDQoH6X899DvQamPintmYlpvm0fGCTpo',
    appId: '1:268722525472:web:56093c26f3da5463a83345',
    messagingSenderId: '268722525472',
    projectId: 'studentapp-440a6',
    authDomain: 'studentapp-440a6.firebaseapp.com',
    storageBucket: 'studentapp-440a6.appspot.com',
    measurementId: 'G-EZT1MEQ4V4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh3SNUm6krO8onWRqmR3PiHkkQtOYXoN0',
    appId: '1:268722525472:android:53de847037a945e8a83345',
    messagingSenderId: '268722525472',
    projectId: 'studentapp-440a6',
    storageBucket: 'studentapp-440a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQsDRLw18LQx9qzO0JMzCE1OzeXndHYAY',
    appId: '1:268722525472:ios:2552a66ff8291deca83345',
    messagingSenderId: '268722525472',
    projectId: 'studentapp-440a6',
    storageBucket: 'studentapp-440a6.appspot.com',
    iosBundleId: 'com.example.studentManagementAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQsDRLw18LQx9qzO0JMzCE1OzeXndHYAY',
    appId: '1:268722525472:ios:80d775f9ebbc8d9ea83345',
    messagingSenderId: '268722525472',
    projectId: 'studentapp-440a6',
    storageBucket: 'studentapp-440a6.appspot.com',
    iosBundleId: 'com.example.studentManagementAppFirebase.RunnerTests',
  );
}
